server:
  port: 8084
spring:
  application:
    name: onlineshopping-gateway
  cloud:
    gateway:
      routes:
        - id: onlineshopping-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/customers
